id: P009514
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:35:52.406847
source_metadata:
  id: bdr:W1KG12710
  title: རྡོར་སེམས་ཐུགས་ཀྱི་མེ་ལོང་གི་དབང་ཆོག་དང་ཁྲིད་ཡིག་སོགས།
  author: ''
  volumes:
    21a4eb3ee6864c66920c11c25b93312f:
      image_group_id: I1KG12748
      title: ''
      volume_number: 1
      total_pages: 325
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
