id: I33128D74
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T13:54:39+00:00'
last_modified: '2022-06-08T11:34:14.345996+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12710
  title: རྡོར་སེམས་ཐུགས་ཀྱི་མེ་ལོང་གི་དབང་ཆོག་དང་ཁྲིད་ཡིག་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    325B:
      image_group_id: I1KG12748
      title: ''
      total_pages: 325
      order: 1
      base_file: 325B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
